name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
    - name: Run build & test
      run: ./build.sh Test
      shell: bash
      env: 
        AUTH0FGA__STOREID: ${{ secrets.FGA_STOREID }}
        AUTH0FGA__CLIENTID: ${{ secrets.FGA_CLIENTID }}
        AUTH0FGA__CLIENTSECRET: ${{ secrets.FGA_CLIENTSECRET }}
